# Site settings
title: Pratique de Ruby - Blog Francophone autour de Ruby
email: efflamm.castel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pratique de Ruby
  Blog Francophone autour du langage de programmation Ruby créé en 1995
  par Yukihiro "Matz" Matsumoto et de son environnement (Ruby on Rails, sinatra...)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://floum.github.io" # the base hostname & protocol for your site
github_username: floum

# Build settings
markdown: kramdown
