# Site settings
title: Naming Convention
email: efflamm.castel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog francophone sur les techniques et bonnes pratiques de développement logiciel
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://floum.github.io" # the base hostname & protocol for your site
github_username: floum

# Build settings
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
